-matrix는 2차원까지만 array는 그 이상을 만들수 있다. 따라서 array를 사용한다.
-행렬곱셉은 A*B일 때, 행렬 A의 렬과 행렬 B의 행을 같게 해줘야 한다.
-dot과 matmul은 2차원에서는 같지만 3차원 이상부터는 값이 다르다.
-dot과 matmul 표현
 1)np.dot(A,B) = A*B
 2)np.matmul(A,B) = A@B

In [93]:
import numpy as np

In [68]:
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
data = np.array(data)
#다른방식
data = np.arange(1,13).reshape(4,3)

In [69]:
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
np.array([1,2,3])

array([1, 2, 3])

In [71]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
#차원수 확인하기
data.ndim

2

In [37]:
data.shape

(4, 3)

In [38]:
data.dtype

dtype('int32')

In [39]:
#행렬의 행값 가져오기
data[0]

array([1, 2, 3])

In [40]:
#행렬의 행,열에 특정값 가져오기
data[0][2]

3

In [41]:
#행렬의 행,열에 특정값 가져오기
data[0,2]

3

In [42]:
#행, 열에 특정값 변경하기
data[0,2] = 1

In [43]:
data

array([[ 1,  2,  1],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
temp = [1,2,3,4,5]
temp = np.array(temp)

In [45]:
data[data>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
#조건값에 따라 값 변경하기
data[data>3] = 3

In [48]:
#구조 바꾸기
data.reshape(2, 6)

array([[1, 2, 1, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [49]:
data.reshape(12)

array([1, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [50]:
#임버스 행렬
data.T

array([[1, 3, 3, 3],
       [2, 3, 3, 3],
       [1, 3, 3, 3]])

In [51]:
#제곱근 구하기
np.sqrt(data)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081]])

In [52]:
#제곱 구하기
np.square(data)

array([[1, 4, 1],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [76]:
#행렬곱셉하기 : data가 (4,3)행렬이니 행렬곱을 위해서는 (3, X)행렬과 곱 필요
A = np.arange(6).reshape(3,2)
data.dot(A)
#다른 방식의 

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103]])

In [77]:
#다른 방식의 행렬곱셈
np.dot(data, A)

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103]])

In [80]:
np.dot(data, A) = np.dot(A, data)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [81]:
#matmul과 dot의 차이
np.matmul(data, A)

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103]])

In [82]:
np.dot(data, A)

array([[ 16,  22],
       [ 34,  49],
       [ 52,  76],
       [ 70, 103]])

In [83]:
#dot은 상수 곱 가능, matmul은 상수 곱 불가능
np.dot(data, 2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [84]:
np.matmul(data ,2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [86]:
#dot과 matmul은 3차원 이상을 때 다른 결과값을 갖는다.
B = np.arange(2*2*4).reshape(2,2,4)
C = np.arange(2*4*2).reshape(2,4,2)

In [92]:
np.dot(B,C)
np.dot(B,C).shape

(2, 2, 2, 2)

In [91]:
np.matmul(B,C)
np.matmul(B,C).shape

(2, 2, 2)